Modules/Crawler/Routes/web.php
<?php

Route::get('/', 'CrawlerController@index');

Route::prefix('crawler')->as('crawler.')->group(function() {
    Route::resource('/search', 'CrawlerController', [
        'except' => [
            'show', 'create', 'update',
        ],
    ]);
    Route::get('/search/scrap', 'CrawlerController@scrap')->name('scrap');
    Route::post('/search/scrap-via-mail', 'CrawlerController@scrapViaMail')->name('scrap_via_mail');
});

Modules/Crawler/Entities/Link.php
<?php

namespace Modules\Crawler\Entities;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Link
 */
class Link extends Model
{
    /**
     * @var bool
     */
    public $timestamps = true;

    /**
     * @var array
     */
    protected $fillable = [
        'search_link',
        'link',
    ];
}

Modules/Crawler/Entities/LinkCrawlerData.php
<?php

namespace Modules\Crawler\Entities;

/**
 * Class LinkCrawlerData
 */
class LinkCrawlerData
{
    /**
     * @var int
     */
    private $count = 0;

    /**
     * @var array
     */
    private $linksFound = [];

    /**
     * @var array
     */
    private $linksFoundWithNoFollow = [];

    /**
     * @var array
     */
    private $linksNotFound = [];

    /**
     * @return int
     */
    public function getCount(): int
    {
        return $this->count;
    }

    /**
     * @return LinkCrawlerData
     */
    public function increaseCount(): LinkCrawlerData
    {
        $this->count++;

        return $this;
    }

    /**
     * @return array
     */
    public function getLinksFound(): array
    {
        return $this->linksFound;
    }

    /**
     * @param string $linksFound
     * @return LinkCrawlerData
     */
    public function putLinksFound(string $linksFound): LinkCrawlerData
    {
        $this->linksFound[] = $linksFound;

        return $this;
    }

    /**
     * @return array
     */
    public function getLinksFoundWithNoFollow(): array
    {
        return $this->linksFoundWithNoFollow;
    }

    /**
     * @param string $linksFoundWithNoFollow
     * @return LinkCrawlerData
     */
    public function putLinksFoundWithNoFollow(string $linksFoundWithNoFollow): LinkCrawlerData
    {
        $this->linksFoundWithNoFollow[] = $linksFoundWithNoFollow;

        return $this;
    }

    /**
     * @return array
     */
    public function getLinksNotFound(): array
    {
        return $this->linksNotFound;
    }

    /**
     * @param string $linksNotFound
     * @return LinkCrawlerData
     */
    public function putLinksNotFound(string $linksNotFound): LinkCrawlerData
    {
        $this->linksNotFound[] = $linksNotFound;

        return $this;
    }
}

Modules/Crawler/Http/Controllers/CrawlerController.php
<?php

namespace Modules\Crawler\Http\Controllers;

use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\View\View;
use Modules\Crawler\Http\Requests\CrawlerFormRequest;
use Modules\Crawler\Http\Requests\ScrapViaMailRequest;
use Modules\Crawler\Repositories\LinkRepository;
use Modules\Crawler\Services\CrawlerMailService;
use Modules\Crawler\Services\CrawlerService;
use Throwable;

/**
 * Class CrawlerController
 */
class CrawlerController extends Controller
{
    /**
     * @var LinkRepository
     */
    private $linkRepository;

    /**
     * @var CrawlerService
     */
    private $crawlerService;

    /**
     * CrawlerController constructor.
     * @param LinkRepository $linkRepository
     * @param CrawlerService $crawlerService
     */
    public function __construct(LinkRepository $linkRepository, CrawlerService $crawlerService)
    {
        $this->linkRepository = $linkRepository;
        $this->crawlerService = $crawlerService;
    }

    /**
     * @return View
     */
    public function index(): View
    {
        $links = $this->linkRepository->all();

        return view('crawler::index', compact('links'));
    }

    /**
     * @param CrawlerFormRequest $request
     *
     * @return RedirectResponse
     */
    public function store(CrawlerFormRequest $request): RedirectResponse
    {
        try {
            $this->linkRepository->create([
                'search_link' => $request->getSearchUrl(),
                'link' => $request->getLinkUrl(),
            ]);
        } catch (Throwable $throwable) {
            logger()->error($throwable->getMessage(), $throwable->getTrace());

            return redirect()
                ->back()
                ->with('danger', __('crawler::global.failed_create'));
        }

        return redirect()
            ->back()
            ->with('success', __('crawler::global.success_create'));
    }

    /**
     * @param int $id
     * @return RedirectResponse
     */
    public function destroy(int $id): RedirectResponse
    {
        try {
            $this->linkRepository->delete($id);
        } catch (Throwable $throwable) {
            logger()->error($throwable->getMessage(), $throwable->getTrace());

            return redirect()
                ->back()
                ->with('danger', __('crawler::global.failed_delete'));
        }

        return redirect()
            ->back()
            ->with('success', __('crawler::global.success_delete'));
    }

    /**
     * @param Request $request
     * @return View
     */
    public function scrap(Request $request): View
    {
        $data = $this->crawlerService->scrap();

        return view('crawler::scrap', compact('data'));
    }

    /**
     * @param ScrapViaMailRequest $request
     * @param CrawlerMailService $mailService
     * @return RedirectResponse
     */
    public function scrapViaMail(ScrapViaMailRequest $request, CrawlerMailService $mailService): RedirectResponse
    {
        try {
            $data = $this->crawlerService->scrap();
            $mailService->sendDataMail($data, $request->getEmail());
        } catch (Throwable $throwable) {
            logger()->error($throwable->getMessage(), $throwable->getTrace());

            return redirect()
                ->back()
                ->with('danger', __('crawler::global.failed_sent_mail'));
        }

        return redirect()
            ->back()
            ->with('success', __('crawler::global.success_sent_mail'));
    }
}

Modules/Crawler/Resources/views/index.blade.php
@extends('crawler::layouts.app')

@section('title')
    {{ __('crawler::global.title') }}
@endsection

@section('content')
    <div class="flex-center position-ref full-height">
        <div class="content w-30 m-auto">
            <div class="m-4">
                <form action="{{ route('crawler.search.store') }}" method="POST">
                    @csrf

                    <label for="search-url">{{ __('crawler::global.search_url') }}</label>
                    <input id="search-url" name="search_url" type="text" class="form-control" value="{{ config('crawler.default.search_url') }}" width="100%"/>

                    <br/>

                    <label for="link-url">{{ __('crawler::global.link_url') }}</label>
                    <input id="link-url" name="link_url" type="text" class="form-control" value="" width="100%"/>

                    <br/>

                    <button class="float-right btn btn-success">{{ __('crawler::global.create_crawler_search') }}</button>
                </form>

                <br/>
                <br/>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>{{ __('crawler::global.search_url') }}</th>
                        <th>{{ __('crawler::global.link_url') }}</th>
                        <th>{{ __('crawler::global.actions') }}</th>
                    </tr>
                    </thead>
                    <tbody>
                        @if ($links->count())
                            @foreach ($links as $link)
                                <tr>
                                    <td>{{ $link->search_link }}</td>
                                    <td>{{ $link->link }}</td>
                                    <td>
                                        <form action="{{ route('crawler.search.destroy', $link->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')

                                            <button class="btn btn-danger">{{ __('crawler::global.delete') }}</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach

                            <tr>
                                <td colspan="3">
                                    <a href="{{ route('crawler.scrap') }}" class="btn btn-info" target="_blank">{{ __('crawler::global.scrap') }}</a>

                                    <br/>

                                    <form action="{{ route('crawler.scrap_via_mail') }}" method="POST">
                                        @csrf

                                        <div class="form-group d-inline">
                                            <input id="email" name="email" type="text" class="form-control d-inline"  style="width: 50%" value="{{ config('crawler.default.email') }}" width="50%"/>
                                            <button class="btn btn-danger d-inline">{{ __('crawler::global.scrap_via_mail') }}</button>
                                        </div>
                                    </form>
                                </td>
                            </tr>
                        @else
                           <tr>
                               <td colspan="3">{{ __('crawler::global.empty') }}</td>
                           </tr>
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@stop

Modules/Crawler/Resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <title>@yield('title')</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <link href="/css/app.css" rel="stylesheet">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

    @stack('styles')

    <!-- Scripts -->
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
</head>
<body id="body" class="sidebar-mini skin-blue-light">
<div class="wrapper">
    @if ((isset($messages) && $messages) || !isset($messages))
        @include('crawler::layouts.messages')
    @endif

    @yield('content')
</div>

<script src="/js/basic-view/adminlte.js"></script>

@stack('pre.scripts')
@stack('scripts')
@stack('post.scripts')
</body>
</html>

Modules/Crawler/Resources/views/layouts/messages.blade.php
@if (
        (isset($errors) && count($errors)) ||
        isset($success) ||
        session('success') ||
        isset($danger) ||
        session('danger') ||
        isset($info) ||
        session('info') ||
        isset($warning) ||
        session('warning')
)
<div class="@if(isset($headerDark) && !$headerDark) alert-header-absolute @endif">
    <div class="row">
        <div class="col-md-12 mb-5 @if (isset($padding) && !$padding) p-0 @endif">
            @if (isset($errors) && count($errors))
                <div class="alert alert-danger">
                    <ul class="mb-0">
                        @foreach ($errors->all() as $error)
                            <li class="list-unstyled mb-0">{{ $error }}</li>
                        @endforeach
                    </ul>
                    <div class="float-right">
                        <i class="fas fa-times-circle" style="color: red; cursor: pointer;" data-dismiss="alert"></i>
                    </div>
                </div>
            @endif

            @if(isset($success))
                <div class="alert alert-success" role="alert">
                    {{ $success }}
                    <div class="float-right">
                        <i class="fas fa-times-circle" style="color: red; cursor: pointer;" data-dismiss="alert"></i>
                    </div>
                </div>
            @endif

            @if(session('success'))
                <div class="alert alert-success" role="alert">
                    {{ session('success') }}
                    <div class="float-right">
                        <i class="fas fa-times-circle" style="color: red; cursor: pointer;" data-dismiss="alert"></i>
                    </div>
                </div>
            @endif

            @if(isset($danger))
                <div class="alert alert-danger" role="alert">
                    {{ $danger }}
                    <div class="float-right">
                        <i class="fas fa-times-circle" style="color: red; cursor: pointer;" data-dismiss="alert"></i>
                    </div>
                </div>
            @endif

            @if(session('danger'))
                <div class="alert alert-danger" role="alert">
                    {{ session('danger') }}
                    <div class="float-right">
                        <i class="fas fa-times-circle" style="color: red; cursor: pointer;" data-dismiss="alert"></i>
                    </div>
                </div>
            @endif

            @if(isset($info))
                <div class="alert alert-info" role="alert">
                    {{ $info }}
                    <div class="float-right">
                        <i class="fas fa-times-circle" style="color: red; cursor: pointer;" data-dismiss="alert"></i>
                    </div>
                </div>
            @endif

            @if(session('info'))
                <div class="alert alert-info" role="alert">
                    {{ session('info') }}
                    <div class="float-right">
                        <i class="fas fa-times-circle" style="color: red; cursor: pointer;" data-dismiss="alert"></i>
                    </div>
                </div>
            @endif

            @if(isset($warning))
                <div class="alert alert-warning" role="alert">
                    {{ $warning }}
                    <div class="float-right">
                        <i class="fas fa-times-circle" style="color: red; cursor: pointer;" data-dismiss="alert"></i>
                    </div>
                </div>
            @endif

            @if(session('warning'))
                <div class="alert alert-warning" role="alert">
                    {{ session('warning') }}
                    <div class="float-right">
                        <i class="fas fa-times-circle" style="color: red; cursor: pointer;" data-dismiss="alert"></i>
                    </div>
                </div>
            @endif
        </div>
    </div>
</div>
@endif

Modules/Crawler/Resources/views/scrap.blade.php
@extends('crawler::layouts.app')

@section('title')
    {{ __('crawler::global.scrap') }}
@endsection

@section('content')
    <div class="flex-center position-ref full-height">
        <div class="content w-30 m-auto">
            <div class="m-4">
                <h3>{{ __('crawler::global.count') }}</h3>

                <p>{{ __('crawler::global.found_links_count') }} {{ $data->getCount() }}</p>
                <p>{{ __('crawler::global.found_links_with_nofollow_count') }} {{ count($data->getLinksFoundWithNoFollow()) }}</p>
                <p>{{ __('crawler::global.not_found_links_count') }} {{ count($data->getLinksNotFound()) }}</p>

                <h3>{{ __('crawler::global.found_links_with_nofollow') }}</h3>
                @foreach ($data->getLinksFoundWithNoFollow() as $key => $link)
                    <a href="{{ $link }}" target="_blank">{{ $key }}. {{ $link }}</a>
                @endforeach

                <h3>{{ __('crawler::global.not_found_links') }}</h3>
                @foreach ($data->getLinksNotFound() as $key => $link)
                    <a href="{{ $link }}" target="_blank">{{ $key }}. {{ $link }}</a>
                @endforeach
            </div>
        </div>
    </div>
@stop